// ? Import Libraries
import type { Metadata } from "next";

// ? Import Slice
import "./styles/globals.css";
import "./styles/normalize.css";
import cls from "./layout.module.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cls.layout}>
          <div>
            header
          </div>
          {children}
      <footer>footer</footer>
      </body>
    </html>
  );
}
