// ? Import Libraries
import type { Metadata } from "next";

// ? Import Widgets
import { Header } from "@/widgets/Header";

// ? Import Slice
import "./styles/globals.css";
import "./styles/normalize.css";
import cls from "./layout.module.scss";
import StoreProvider from "./providers/StoreProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (

        <html lang="en">
            <body className={cls.layout}>
                <StoreProvider>
                    <Header />
                    {children}
                    <footer></footer>
                </StoreProvider>
            </body>
        </html>
  );
}
